/**
 * Redux Action类型常量定义
 */

// 用户认证相关
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

// 游记相关
export const FETCH_TRIPS_REQUEST = 'FETCH_TRIPS_REQUEST'
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS'
export const FETCH_TRIPS_FAILURE = 'FETCH_TRIPS_FAILURE'
export const CREATE_TRIP_REQUEST = 'CREATE_TRIP_REQUEST'
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS'
export const CREATE_TRIP_FAILURE = 'CREATE_TRIP_FAILURE'
export const UPDATE_TRIP_REQUEST = 'UPDATE_TRIP_REQUEST'
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS'
export const UPDATE_TRIP_FAILURE = 'UPDATE_TRIP_FAILURE'
export const DELETE_TRIP_REQUEST = 'DELETE_TRIP_REQUEST'
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS'
export const DELETE_TRIP_FAILURE = 'DELETE_TRIP_FAILURE'

// 审核相关
export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST'
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS'
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE'
export const APPROVE_REVIEW_REQUEST = 'APPROVE_REVIEW_REQUEST'
export const APPROVE_REVIEW_SUCCESS = 'APPROVE_REVIEW_SUCCESS'
export const APPROVE_REVIEW_FAILURE = 'APPROVE_REVIEW_FAILURE'
export const REJECT_REVIEW_REQUEST = 'REJECT_REVIEW_REQUEST'
export const REJECT_REVIEW_SUCCESS = 'REJECT_REVIEW_SUCCESS'
export const REJECT_REVIEW_FAILURE = 'REJECT_REVIEW_FAILURE'